FROM alpine:3.20

RUN apk add --no-cache \
    libpcap \
    ca-certificates

RUN adduser -D -H foxd

WORKDIR /app

COPY foxd /usr/local/bin/foxd

RUN chmod +x /usr/local/bin/foxd

USER foxd

EXPOSE 3090

ENTRYPOINT ["foxd"]