FROM alpine:3.20

RUN apk add --no-cache \
    libpcap libcap \
    ca-certificates

RUN adduser -D -H foxd

WORKDIR /app

COPY foxd /usr/local/bin/foxd

RUN chmod +x /usr/local/bin/foxd \
    && setcap cap_net_raw,cap_net_admin=eip /usr/local/bin/foxd

USER foxd

ENTRYPOINT ["foxd"]